### ISSUE TITLE
Question: AngularJS in frontend

### ISSUE THREAD

**Issue by MilosStanic** [gergo85/oc-frontend-plugins#1]
Hello, 

I see in the docs that AngularJS is one of the supported plugins. 

I need to have an AngularJS single page app as part of my October site. I want this page to be protected by October's login system. 

How would I create such a page?

I need, naturally, to load my own AngularJS application scripts. I'm guessing I would need to put them somewhere in the `/storage` folder, I just don't know where exactly. Such folder would also need to contain the full directory structure for an AngularJS app, including views and partials, and css. 

How do I resolve templating conflict between Twig and AngularJS regarding double curly brackets `{{ }}`? 

Thanks a lot.

**Comment by gergo85** [comment]
Hi,

The Frontend Plugins scan the source code of layout and find the javascript file of AngularJS. It is the basic method, there is not special AngularJS support.

I have never use the AngularJS in OctoberCMS so I have no idea, how to do it. I recommended you should use the official support area: http://octobercms.com/support

I hope you will find the solution.

**Comment by MilosStanic** [comment]
Thanks, I found a solution for serving an AngularJS app here
https://github.com/responsiv/angular-plugin

Closing.
